version: "2"
services:
  xlu_web:
    image: nginx
    networks:
      - internal
    volumes:
      - $PWD/nginx.conf:/etc/nginx/conf.d/default.conf
      - $PWD/xlu_web:/usr/share/nginx/html
    command: /bin/bash -c "nginx -g 'daemon off;'"
    labels:
      - "traefik.frontend.rule=Host:xlu.julu666.com"

networks:
  internal:
    external: true